### ISSUE TITLE
Bot crashes when trying to send audiomessage

### ISSUE THREAD

**Issue by ZemlyakovDmitry** [Flittis/Lua_VK_ModuleBot#2]
1. Select any conversation
2. Write command to send audiomessage (example - !pavel)

FR - Bot crashed
ER - Bot will send audiomedssage 

 https://pastebin.com/XFsXSrhb

**Comment by Flittis** [comment]
**curl_mime_init() was introduced in libcurl 7.56.0.**

Try update curl and libcurl:
```
-$ sudo apt update
-$ sudo apt upgrade
-$ sudo apt install curl libcurl4
```
